### ISSUE TITLE
Mention failing gem in error message

### ISSUE THREAD

**Issue by Confusion** [e2/ruby_dep#24]
In https://github.com/guard/listen/issues/409 I noted that ruby_dep causes a `bundle install` to fail with

```
Gem::InstallError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```

It would have been extremely helpful for me if this error message had mentioned which gem was being installed and had this dependency. As it is, I spent quite some time figuring out that `listen` was the gem that was failing.

Would it be possible to include the gem that has the dependency, and raises the error, in this message?

**Comment by e2** [comment]
I'm not sure how to do that without monkey-patching `rubygems`.

The best way is to do something like: `gem dependency|grep -B 5 "  ruby_dep"`.

**Comment by e2** [comment]
I'm closing this, because this version checking is happening before RubyDep even initializes - so I can't think of anything I can really do.

If RubyDep actually did require Ruby 2.2.5 to work properly (for whatever reason), then it would be up to Bundler to add information about which gem requires this one.

As a user, you want to know that if a required gem cannot be installed because of a Ruby version, you may want a different version of the gem requiring it (e.g. `listen`).

So this is more of a `rubygems`/`bundler` feature to be more user friendly. I'm sure other gems would benefit once more people start using Ruby 2.3-only or Ruby 2.4-only features.

**Comment by Confusion** [comment]
Ah, I thought ruby_dep raised an error during its installation causing bundler to fail, but I now understand it's bundler itself that checks the version dependency and fails. OK, I'll take it up with them then.

> The best way is to do something like: gem dependency|grep -B 5 " ruby_dep".

There's a chicken/egg problem there: if bundler fails, the gem isn't installed, so you can't grep its dependencies either.
