### ISSUE TITLE
Propagation of RubyDep::Travis.new.version_constraint to application if used in deps

### ISSUE THREAD

**Issue by petrblaho** [e2/ruby_dep#3]
In our project (https://github.com/ManageIQ/manageiq) we use additional developer specific gemfile loading - https://github.com/ManageIQ/manageiq/blob/master/Gemfile#L127-L141

I personally use `guard` and `pry` so my `Gemfile.dev.rb` looks like:

``` ruby
gem 'pry-rails'
gem 'pry-byebug'

gem 'guard'
gem 'guard-rspec', require: false
```

`guard` 's dependency `listen` uses `ruby_dep` in https://github.com/guard/listen/blob/master/listen.gemspec#L25-L31

As I understand `ruby_dep` will raise `LoadError` and installation of gems will be interrupted.

I use ruby 2.2.2 and when I run `bundle` I got:

```
Gem::InstallError: ruby_dep requires Ruby version >= 2.2.4, ~> 2.2.
An error occurred while installing ruby_dep (1.1.0), and Bundler cannot continue.
Make sure that `gem install ruby_dep -v '1.1.0'` succeeds before bundling.
```

Is this intended behavior? I understand that authors and maintainers of gems would like to have users use supported versions of ruby only but this seems to be really intrusive feature.

**Comment by e2** [comment]
@petrblaho - thanks for opening this issue.

First, you definitely want to upgrade Ruby to at least 2.2.4, see: https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-2-4-released, so it makes little sense for me to work on fixing that.

Second, upgrade bundler to the newly released version: `gem update bundler`. Bunder v1.12.1 now should automatically install an older version of Listen still supported by your current Ruby version.

Mostly, this is all about being explicit. I don't mind backporting changes to support older versions if there's a good reason. But if e.g. Listen doesn't officially support a given Ruby, I don't want people thinking it does just because "it works" or "it worked".

Currently, Listen doesn't support Ruby <= 2.2.4. There might not be a reason why it doesn't, but it shouldn't be installable until it officially does.

In this case though, please update to 2.2.4 to avoid the security vulnerability.

(JRuby support is a different story, though).

**Comment by e2** [comment]
> this seems to be really intrusive feature

I agree. And the downside is still minor compared to the benefits and avoided bigger problems.

The "argument" is that: if people don't want backward compatibility, they should not upgrade anything else, either. They should even lock versions very tightly to "what works" to prevent upgrades.

This leaves 2 clear strategies:
1. Upgrade everything you can to stay up to day. (This includes Ruby, because why not?).
2. Upgrade nothing and very carefully update gems patch-level by patch-level, request backports, justify the need, lock to specific gem versions, carefully track security vulnerabilities.

I want to prevent other behaviors such as: "I don't think security is important, so I don't need to upgrade my Ruby, so I expect gem maintainers to forever stay backward compatible with what I already have installed - until I'm actually forced to upgrade my OS". Because such behavior hurts everyone in the long run.

Feel free to open issues - I do want to make things as seamless as I can. If you have a problem/concern and there's no issue for it - I likely don't know about it.

**Comment by e2** [comment]
I'm closing this, because the propagation only happens if you upgrade a library or a dependency. (You still have the choice of not upgrading by locking to an earlier version). 

Do let me know if you disagree.

Otherwise, tools like Bundler should help you install a "working" set of dependencies for your Ruby version, no matter how old.

There's also no "other" way to notify users of a vulnerable Ruby, really. 

E.g. RubyGems does warn about gemspec problems, whether users like those warnings or not. So this is similar, except it's done through a gem because the functionality isn't present anywhere else ATM.

**Comment by e2** [comment]
(previous comment updated).

**Comment by thedanbob** [comment]
> Bunder v1.12.1 now should automatically install an older version of Listen still supported by your current Ruby version.

FWIW, bundler 1.12.1 doesn't do this – it still happily installs incompatible versions of gems even with the `ruby` directive. It's not clear to me if this is a bug in bundler.

I had the same issue as the original reporter when I updated my gems. The solution was of course to restrict my version of `listen`, which is fine, but it took me a while to figure out that was the issue because there was no obvious way to tell which gem depended on `ruby_dep`. I happen to fall into a third upgrade strategy: upgrade everything possible, but not ruby because our production servers are limited to 2.1.

I think this gem is a good idea, but shouldn't the gem itself not have a restriction on the ruby version? Otherwise, how could another gem that wanted to support an older ruby be able to use it?

**Comment by e2** [comment]
@danbob - thanks. I suspect Bundler doesn't handle resolving too well along with Ruby version specifications. There's also JRuby, which complicates things further.

> It's not clear to me if this is a bug in bundler.

Probably worth reporting. There might be issues which probably can't be solved until Bundler 2.x, so that may be a problem.

> it took me a while to figure out that was the issue because there was no obvious way to tell which gem depended on ruby_dep.

I'd use something like:

``` bash
$ for k in $(gem list --no-versions); do gem specification $k|grep -q ruby_dep && echo $k; done
listen
ruby_dep
```

> I happen to fall into a third upgrade strategy: upgrade everything possible, but not ruby because our production servers are limited to 2.1.

You should urge to change that. At any moment in time a certain server/os/library/configuration change can trigger an existing "never-to-be-fixed" bug in 2.1. And you'd be left in a situation where workarounds are insanely complex, your app is stuck in a broken state, and upgrading Ruby may be risky even if it's possible.

It's not a good business situation to be in. It's like not making (and testing!) regular backups. Even if few people do it, it doesn't mean it's acceptable not to.

Sure, hosting providers have constant security issues to deal with, and more configuration possibilities than anyone can image. Except, they get paid for doing that, while I don't get for e.g. dealing with JRuby issues, which I don't even care about personally.

Then again, if a vulnerability in Ruby allows remote hackers to run binary code on a hosting platform, even a DoS attack can lead to huge losses in costs and revenue.

Patching Ruby 2.1 even with custom security patches isn't a good strategy either. You can become "super vulnerable" overnight with no quick workaround or patch. The hosting provider should cave in - and no one else.

> I think this gem is a good idea, but shouldn't the gem itself not have a restriction on the ruby version? 

I'm willing to backport to support earlier versions. But I need a compelling use case. Yesterday I added support for Ruby 2.2.3, because that's the latest Ruby API used by the latest available JRuby. I compromised here already, because JRuby wasn't affected by the same vulnerability as MRI 2.2.3. But, at least users get a warning if they install on MRI 2.2.3.

So, yesterday I added "backward-compatibility" for MRI 2.2.3. But there was a good use case for it: to allow it to install on JRuby 9.0.5.0 for testing. (9.0.4.0 uses Ruby API 2.2.2).

So "not supported" means "not supported at the moment". I don't want to "fool" people into thinking something is supported which isn't. (Like JRuby on Listen, as it turned out).

Also, it's actually ridiculous to support more than one version of an interpreter in a single codebase. If you're interested, read the "Compatibility" section here: http://blog.jruby.org/2015/07/jruby_9000

> Otherwise, how could another gem that wanted to support an older ruby be able to use it?

Supporting "an older ruby" is exactly the root cause of all problems here. Up till now, I don't have a single use case where "supporting an older Ruby" is worth more than the "cost" of upgrading. That wasn't true of migration from Ruby 1.8.7 to Ruby 1.9.3, but going from Ruby 1.9.3 to 2.3.1 is actually trivial.

And with tools like rbenv and RVM, you can install any Ruby as any user, really. Some production environments may limit you, but it's not like moving from one hosting provider to another costs millions. In some cases, it takes less time than it does for me to wait until the whole Travis build matrix finishes after a single-line commit PR...

Simply put: there is still (as of yet) no compelling use case of supporting an older Ruby. And asking for a backport of a patch isn't hard - I respond very fast with fixes and releases. The release changelogs I create are probably the tiniest you'll ever find. You'll know exactly which patches/fixes you need.

If not, you can always open an issue.

I'm just not paid for backward-compatibility and tracking security issues. I don't mind creating backporting branches for PRs, either.

Sometimes I do even 3 releases a day (if that's how bugs come up). So likely you'll get a PR accepted and released faster than anywhere else. In order to keep things like this, I need to cut some dead weight that no one really needs.

Even then, you still have a choice: to support an older gem, you can just stick to an older version of Listen. Like 2.x even. You can read the changelogs between 2.x and 3.1, pick what you want, create a PR with backports and I can release another 2.x patch without dragging the dead man further.

**Comment by thedanbob** [comment]
> > I happen to fall into a third upgrade strategy: upgrade everything possible, but not ruby because our production servers are limited to 2.1.
> 
> You should urge to change that.

I agree and I've been working on it, but it could take a while. Our infrastructure almost exclusively uses Debian, which is stuck at ruby 2.1.5 in the official repos.

> > I think this gem is a good idea, but shouldn't the gem itself not have a restriction on the ruby version?
> 
> I'm willing to backport to support earlier versions. But I need a compelling use case.

Maybe I'm just missing something, but here's an example of what I'm getting at:

```
$ rvm use 2.2.3
$ gem install listen
Successfully installed rb-fsevent-0.9.7
Successfully installed ffi-1.9.10
Successfully installed rb-inotify-0.9.7
Successfully installed ruby_dep-1.2.0
Successfully installed listen-3.1.3
5 gems installed
$ irb
> require 'listen'
RubyDep: WARNING: your Ruby has security vulnerabilities! Please upgrade! (To disable warnings, set RUBY_DEP_GEM_SILENCE_WARNINGS=1)
 => true
```

```
$ rvm use 2.1.5
$ gem install listen
Successfully installed rb-fsevent-0.9.7
Successfully installed ffi-1.9.10
Successfully installed rb-inotify-0.9.7
ERROR:  Error installing listen:
    ruby_dep requires Ruby version >= 2.2.3, ~> 2.2.
```

I would have expected the result of the second case to be the same as the first case, at least if listen didn't have the >= 2.2.3 restriction as well. If ruby_dep is only going to support ruby >= 2.2.3, I might suggest changing the readme to reflect that—in particular, the Tips section that mentions ruby 1.9, 2.0, etc.

**Comment by e2** [comment]
> Our infrastructure almost exclusively uses Debian, which is stuck at ruby 2.1.5 in the official repos.

Might be best to use this PPA: https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng (For Ruby 2.2.4 at the bare minimum, ideally 2.2.5 at least).

> Maybe I'm just missing something, but here's an example of what I'm getting at:

The vulnerability is this: https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-2-4-released

> I would have expected the result of the second case to be the same as the first case, at least if listen didn't have the >= 2.2.3 restriction as well.

But then RubyDep wouldn't e.g. be able to use 2.2 features. A single usage of such a feature without adequate test coverage (100% is often unrealistic) can just crash production systems. I don't want to be responsible neither for accidentally writing that code nor being sufficiently "careful".

Simply put, currently Ruby 2.1.5 is neither supported by `ruby_dep`, nor by `listen`. Support could be added for backports, but I don't have a personal need to support Ruby < 2.2. If you have a specific case, we can discuss it in a separate issue. (If I agree to add support for a specific earlier version of Ruby, I'll obviously relax `ruby_dep`'s dependencies and added the right Ruby versions to the Travis build matrix for both projects.

E.g. supporting Ruby 2.1.5 specifically isn't a good idea, see: https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-1-8-released

So supporting 2.1.8 is the minimum, and 2.1.9 is recommended to avoid as many bugs as possible. (I'm assuming such a server will run longer than just a few days - if it's going to be months, you might as well catch the latest compatible version available).

I'm guessing Ruby 2.1.8 would already be a problem for you. Which just shows how deep the rabbit hole goes on your hosting provider's side. Of all things, they should be at least able to seamlessly upgrade from 2.1.5 to 2.1.8. It's not like they have their own Ruby that's more than 20% different from the official Ruby.

So `Listen` has the 2.2.3 restriction (2.2.4 if it wasn't for JRuby) for good reasons - to support something reasonable. Everything else should be discussed, because there's probably a bigger problem than just "that's the version I'm stuck with".

I'm not sure which versions of Ruby `ruby_dep` will end up supporting (support for older versions can be added with minor version bumps). Personally, I'll want to drop as many Rubies as possible (to avoid supporting Rubies for which there is no real demand). But there might be things like the JRuby case which was unexpected.

Currently, I want `ruby_dep` to "follow it's own process". Which means: it started out at Ruby 2.3, which wasn't practical since Ruby 2.2 is still recommended, then it supported only Ruby >= 2.2.4 (because it was a vulnerability fix) and now it supports 2.2.3 (due to JRuby).

This is the "reverse" of supporting every Ruby and "fixing issues" on newer Ruby versions. By doing so projects accumulate a huge matrix of versions to test, e.g. 1.8.7, 1.9.3, 2.0, 2.1, 2.2, 2.3, jruby-1.8, jruby-1.9, jruby-9k, rbx, rbx-2. And those versions are just the bare "standard". That's 11 different interpreter environments to run on Travis already! Add OSX testing, and you have 22 Travis builds for a simple "hello world" gem. Sure, the codebase is not that complex - but things like specs and RuboCop get really, really hairy very fast. Not to mention: every Travis build has a potentially DIFFERENT set of gems every time. And if you don't make commits regularly, a Travis build will stay "green" for months, even though it wouldn't work anymore if it was restarted.

> I might suggest changing the readme to reflect that—in particular, the Tips section that mentions ruby 1.9, 2.0, etc.

Updated, thanks! The idea is to have the Travis build page show which versions of Ruby are currently supported. Since SemVer allows dropping/adding support for a major interpreter versions with just a patch-level change (a Ruby version is neither "docs" nor "API"), nothing is more reliable to show which versions are intended to be supported than green builds on Travis.

`ruby_dep` can be hacked to allow 1.9.3 - people can simply vendor that gem in their projects if they need to.

Feel free to add/change questions on the Wiki.

**Comment by thedanbob** [comment]
> Might be best to use this PPA: https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng (For Ruby 2.2.4 at the bare minimum, ideally 2.2.5 at least).

I'll check that out, thanks!

> But then RubyDep wouldn't e.g. be able to use 2.2 features. A single usage of such a feature without adequate test coverage (100% is often unrealistic) can just crash production systems. I don't want to be responsible neither for accidentally writing that code nor being sufficiently "careful".

Fair enough. I remember maintaining 1.8 and 1.9 projects simultaneously—THAT was fun.

Thanks for taking the time to help me understand what was going on!

**Comment by e2** [comment]
> I'll check that out, thanks!

Be warned - Ruby 2.3.0 had a show-stopper bug that I managed to trigger during provisioning for production (bad crash at C-level). I'm so happy 2.3.1 was released so soon (I was especially waiting for that one bugfix). Just shows that "backward-compatibility" is much riskier than people imagine.

My thinking is: every minute the ruby-core team spends on backports is time never to be recovered. And 2.3.1 is going to be exciting for servers (definitely money saved on hosting resources).

I strongly believe it's better to make a language survive through fast evolution - rather than for a given interpreter version to "work for years without upgrading". Not upgrading a project is a bit like wishing it would die before the upgrade becomes essential. It's tempting to "stack" upgrades and "do it all in one go". But, upgrade effort becomes tougher to estimate - which is a huge business risk.

Anyway ...

> I remember maintaining 1.8 and 1.9 projects simultaneously—THAT was fun.

Working on Thread and Fiber support for various combinations of MRI, JRuby and Rubinius was ... ehm... "exciting". Tons of hours spent debugging something already fixed in a newer version (or on HEAD which hasn't had a release for weeks or months). I never was happier working on the cutting edge than when using a fresh jruby-head every 2-3 days with a merged bugfix for something I just reported days or hours prior. 

As for Ruby 1.8 vs 1.9, most of the "fun" was reverting the habitual JSON 1.9 hash syntax to 1.8. Most pointless waste of 5 minutes every time. Builds broken because of hash syntax. (Or stuff like that). And some differences in Hash related methods too. Encodings were great implementation-wise. I just wish Ruby had them right from the start.

I feel that every time someone asks to support Ruby 1.8.7, baby seals die or something... It's just a waste given all the benefits of Ruby 1.9.3 and later. And I don't want to enter my credit card info on a site running 1.9.3. 

So I prefer to be bold and "nudge" people to make the upgrade sooner - the world will be a bit better. Definitely.

> Thanks for taking the time to help me understand what was going on!

Yeah, sure. I'm getting good at it. LOTS of "practice" lately, lol ...

Enough of my ranting for now. Time to fix JRuby and then start working on something useful, like "features".

**Comment by e2** [comment]
RubyDep has been updated to be installable on Ruby 2.0.0 (for OSX 10.10).

On Ruby >= 2.0.0 this means `ruby_dep` can be installed, which means the installation error will be for Listen (which requires Ruby >= 2.2.3 right now). This should be less confusing to users, since most won't know what `ruby_dep` is or what's pulling it.

It also shows the current version, so users accidentally using the system Ruby will have more clues as to what's going wrong.

Also, `ruby_dep` now shows recommendations on which Ruby to install or switch to.

I also reworked the documentation for `ruby_dep`, so I hope it's clearer what it does and what it's for.

I do care about making updating/migration easier for users, so if there's anything I could do here to "guide" users towards upgrading, do share your ideas with me (through new issues ideally - so I can keep track and respond/implement one by one).

E.g. depending on the OS, I could show instructions about how to obtain the recommended Rubies (e.g. redirecting to homebrew tutorial depending on OSX version).

If you have experiences/suggestions, feel free to add ideas alongside existing ones here: https://github.com/e2/ruby_dep/issues. (Or vote on existing ones).

@danbob - I'd remove the restriction on the remaining Rubies (1.8 and 1.9), but I'm not sure there any benefit/need. (I do want a good reason first).
